### ISSUE TITLE
New version 0.5 for cocoapods

### ISSUE THREAD

**Issue by colasjojo** [mapedd/TKRoundedView#5]
Could you update the last version for cocoapods?
I can do it for you if you want! (I'll try) Ask me if you want me to do so.

Thanks

**Comment by colasjojo** [comment]
Hi @mapedd, do you plan updating your pod with the above step by step help?

**Comment by mapedd** [comment]
Hi mate
I will do it tomorrow at latest, pinky promise :D

**Comment by colasjojo** [comment]
Thanks ;-)

**Comment by mapedd** [comment]
Can you check now? I managed to push to trunk and then i tried installing it (ver 0.5) in a different project as a pod - it worked :P

**Comment by colasjojo** [comment]
Yes it works! Thanks for having taken the time to do it!

**Comment by mapedd** [comment]
Sorry that it took me so much time. It was tough couple of months :-1:

**Comment by colasjojo** [comment]
Don't be sorry! You are very generously working for the community!
